# Generated by Django 5.2.8 on 2025-11-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('BROKEN', 'Broken'), ('PENDING', 'Pending Approval'), ('UNDER_REPAIR', 'Under Repair'), ('ARCHIVED', 'Archived')], default='AVAILABLE', max_length=50),
        ),
    ]
